export const prefix = "mox";

// We export the spaces so it can be used to generate clamp-spaces in `generateCss.ts`
export const spaces = [
  "4xs",
  "3xs",
  "2xs",
  "xs",
  "sm",
  "md",
  "lg",
  "xl",
  "2xl",
  "3xl",
  "4xl",
] as const;

export const globalSizeOptions = [
  "0",
  "auto",
  "inherit",
  "fit-content",
  "max-content",
  "min-content",
] as const;

export const globalGapOptions = ["0", "auto", "inherit"] as const;

export const colorOptions = [
  "primary",
  "primary-hover",
  "primary-subtle",
  "primary-subtle-hover",
  "primary-subtle-2",
  "primary-subtle-2-hover",
  "secondary",
  "secondary-hover",
  "secondary-subtle",
  "secondary-subtle-hover",
  "secondary-subtle-2",
  "secondary-subtle-2-hover",
  "neutral",
  "neutral-hover",
  "neutral-subtle",
  "neutral-subtle-hover",
  "neutral-subtle-2",
  "neutral-subtle-2-hover",
  "accent",
  "accent-hover",
  "accent-subtle",
  "accent-subtle-hover",
  "accent-subtle-2",
  "accent-subtle-2-hover",
  "info",
  "info-hover",
  "info-subtle",
  "info-subtle-hover",
  "info-subtle-2",
  "info-subtle-2-hover",
  "success",
  "success-hover",
  "success-subtle",
  "success-subtle-hover",
  "success-subtle-2",
  "success-subtle-2-hover",
  "warning",
  "warning-hover",
  "warning-subtle",
  "warning-subtle-hover",
  "warning-subtle-2",
  "warning-subtle-2-hover",
  "error",
  "error-hover",
  "error-subtle",
  "error-subtle-hover",
  "error-subtle-2",
  "error-subtle-2-hover",
  "zwart",
  "wit",
  "transparant",
] as const;
